### ISSUE TITLE
Integration tests failing with 5.0.1 and 5.0.2 (5.0.0 is working)

### ISSUE THREAD

**Issue by Sickboy78** [ioBroker/testing#640]
Hi!

my integration tests will fail, when I upgrade @iobroker/testing to 5.0.1 or 5.0.2 with:
`
      "before all" hook: prepareTests in "Adapter integration tests":
     TypeError: (0 , objects_1.entries) is not a function or its return value is not iterable
      at AdapterSetup.installAdapterInTestDir (node_modules\@iobroker\testing\build\tests\integration\lib\adapterSetup.js:103:60)
      at async Context.prepareTests (node_modules\@iobroker\testing\build\tests\integration\index.js:73:9)
`
see https://github.com/Sickboy78/ioBroker.sureflap/actions/runs/12915451728/job/36017361053?pr=156
They are working fine with 5.0.0.
Any help would be appreciated!

Best Regards
Sebastian

**Comment by mcm1957** [comment]
same here: https://github.com/simatec/ioBroker.solax/actions/runs/12915319734/job/36016931916

**Comment by GermanBluefox** [comment]
Please test 5.0.3

**Comment by Sickboy78** [comment]
Unfortunately the error just changed with 5.0.3:
`
       "before all" hook: prepareTests in "Adapter integration tests":
     TypeError: this._statesClient.delStateAsync is not a function
      at DBConnection.delState (node_modules\@iobroker\testing\build\tests\integration\lib\dbConnection.js:92:39)
      at AdapterSetup.deleteOldInstances (node_modules\@iobroker\testing\build\tests\integration\lib\adapterSetup.js:149:32)
      at async Context.prepareTests (node_modules\@iobroker\testing\build\tests\integration\index.js:78:9)
`

**Comment by hombach** [comment]
same - 5.0.3 also not working

**Comment by mcm1957** [comment]
@Sickboy78 @hombach 
Interesting. Please provide a link to the runs.
5.0.3 is working at least in some setups.

**Comment by mcm1957** [comment]
@Sickboy78 
You are not using standard workflow and not using components ioBroker/testing-action-check and ioBroker/testing-action-adapter. Maybe you private setup is no longer fully compatible with iobroker/testing.

Please consider using standard test environment. An up to date test-and-release workflow can be found at ioroker.iobroker.examples repo.

At least please check wether standard workflow works or fail too so that we get more information about the problem and its reason.

**Comment by Sickboy78** [comment]
@mcm1957 
I updated the github test-and-release workflow to the latest version from the examples repo and it works now with 5.0.3 in github:
https://github.com/Sickboy78/ioBroker.sureflap/actions/runs/13039861884
Strange enough it's still not working locally.
When started with _npm run test:integration_ it still gives this error:
`
  1) Adapter integration tests
       "before all" hook: prepareTests in "Adapter integration tests":
     TypeError: this._statesClient.delStateAsync is not a function
      at DBConnection.delState (node_modules\@iobroker\testing\build\tests\integration\lib\dbConnection.js:92:39)
      at AdapterSetup.deleteOldInstances (node_modules\@iobroker\testing\build\tests\integration\lib\adapterSetup.js:149:32)
      at async Context.prepareTests (node_modules\@iobroker\testing\build\tests\integration\index.js:78:9)
`
Tested with Node versions  20.12.2, 20.18.2 and 22.13.1.
It's working with 5.0.0 though.
Any idea what could be the problem locally?

**Comment by mcm1957** [comment]
just to be sure
you executed a npm i locally to update?

maybe you could delete the node_modules tree an reload it using npm i

for tests you coul pull the working github versionninto a new local directory and check if it works.

Otherwise i do not have a real idea. ev check uf you installed something globally which causeus a conflict.

**Comment by mcm1957** [comment]
hmmm...
could check how the action packages start the test. maybe theres a difference.

I m on mobile only. Maybe i can have look tomorrow

**Comment by hombach** [comment]
By deleting "type-checking: true" in test-and-release workflow it's working in GITHUB - but locally I still have a type-checking and there I get:
```
Adapter integration tests
       "before all" hook: prepareTests in "Adapter integration tests":
     TypeError: this._statesClient.delStateAsync is not a function
      at DBConnection.delState (node_modules\@iobroker\testing\build\tests\integration\lib\dbConnection.js:92:39)
      at AdapterSetup.deleteOldInstances (node_modules\@iobroker\testing\build\tests\integration\lib\adapterSetup.js:149:32)
      at async Context.prepareTests (node_modules\@iobroker\testing\build\tests\integration\index.js:78:9)
```

**Comment by Sickboy78** [comment]
@mcm1957 
Yes, I deleted node_modules before running _npm install_.
I also tried _npm cache clean --force_ and deleting _%LocalAppData%/npm-cache_ manually to no avail.
I cloned my adapter into a differnet folder, didn't work either.
And now it gets even stranger.
I installed node on a clean system where no node was installed before and checked out my adapter.
Run _npm install_ and _npm run test:integration_.
And it worked.
**Exactly once**.
I couldnt believe it, so I just run _npm run test:integration_ again (without changing anything or even executing another command).
And it failed. Same error as above.
I have not been able to get it to work again since then.
I cleared all the caches and deleted node_modules, even uninstalled and reinstalled node and npm.
But that would probably explain, why it is working on github, because the tests are always run on a clean instance.
I'm not a nodejs pro, so any idea where the wrong bit hides, even after a node uninstall and deleting all the caches?

**Comment by Garfonso** [comment]
For further tests, you can try to remove the test-YOURADAPTERNAMEHERE folder from your temporary directory. In Windows, this should be somewhere in `C:\users\YOURUSERNAME\AppData\Local_Low\Temp` or so.

**Comment by Sickboy78** [comment]
> For further tests, you can try to remove the test-YOURADAPTERNAMEHERE folder from your temporary directory. In Windows, this should be somewhere in `C:\users\YOURUSERNAME\AppData\Local_Low\Temp` or so.

Yes, thats it. Deleting C:\users\USERNAME\AppData\Local\Temp\test-ADAPTERNAME lets you run the integration tests successful.

**Comment by hombach** [comment]
SAME - Deleting files in %temp% helps once. I had to disable this also in GIT. 5.0.3 dosn't work. Rolling back to 5.0.0.

**Comment by hombach** [comment]
ok, that's new.... roll back to 5.0.0 + deleting everything + nom install to renew dependecies doesn't help anymore.... I can only remove integration tests at all

**Comment by mcm1957** [comment]
@hombach 

Do you still have any problem with tests. I'm not aware that there is some general issue.

**Comment by Sickboy78** [comment]
I am currently running 5.0.4 and am not having the issues I had with 5.0.1, 5.0.2 and 5.0.3.
The integration tests are running successfully on Github and locally with no manual cleanup required between executions.

**Comment by mcm1957** [comment]
Thanks for info. Issue could be closed.

@Sickboy78 If you have time please close Issue - I dont have required rights

**Comment by hombach** [comment]
Same for me 5.0.4 works fine again - locally and GIT

**Comment by Sickboy78** [comment]
Issue resolved with version 5.0.4.
